FoodBook/FoodBook/urls.py
from django.conf import  settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RecipeAndProduct.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

FoodBook/accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView
from .views import MyLogoutView,RegisterUser,AboutMeView, UserUpdateView

app_name='accounts'

urlpatterns = [
    path('login/', LoginView.as_view(
            template_name='accounts/login_myauth.html',

        ), name='login_app'),
    path('logout/', MyLogoutView.as_view(), name='Logout_app'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('about-me/', AboutMeView.as_view(), name='about_me'),
    path('about-me/update', UserUpdateView.as_view(), name='about_me_update'),
]

FoodBook/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

def profile_path_name(instens:'Profile', filename:str) -> str:
    return "profile/profile_{pk}/avatar/{filename}".format(
        pk=instens.pk,
        filename=filename,
    )

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=500, blank=True)
    argumet_acsepted = models.BooleanField(default=False)
    avatar  = models.ImageField(null=True, blank=True, upload_to=profile_path_name)

FoodBook/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserAndProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].widget.attrs['class'] = 'form-control'
            if self.fields[field_name].label == "Электронная почта":
              self.fields[field_name].widget.attrs['type'] = 'email'

        if self.instance and self.instance.pk:
            self.fields['bio'] = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
                                                 label='О себе', required=False, initial=self.instance.profile.bio,
                                                 max_length=500)
            self.fields['argumet_acsepted'] = forms.BooleanField(label='Соглашение', required=False,
                                                                 initial=self.instance.profile.argumet_acsepted)
            if self.instance.profile.avatar:
                self.fields['avatar'] = forms.ImageField(label='Аватар', required=False,
                                                         initial=self.instance.profile.avatar.url,
                                                         widget=forms.ClearableFileInput(
                                                             attrs={'class': 'form-control-file'}))
            else:
                self.fields['avatar'] = forms.ImageField(label='Аватар', required=False,
                                                         widget=forms.ClearableFileInput(
                                                             attrs={'class': 'form-control-file'}))

FoodBook/accounts/views.py
from django.shortcuts import render
from .models import Profile

from django.contrib.auth import authenticate, login

from  django.views.generic import CreateView, TemplateView , UpdateView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import UserCreationForm
from  django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserAndProfileForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User

class RegisterUser(CreateView):
    form_class = UserCreationForm
    template_name = "accounts/register_user.html"
    success_url = reverse_lazy('RecipeAndProduct:recipt-list')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')

        user = authenticate(
            self.request,
            username=username,
            password=password,

        )
        login(request=self.request, user=user)
        return response

class AboutMeView(TemplateView):
    template_name = 'accounts/about-my.html'

class MyLogoutView(LogoutView):
    next_page = reverse_lazy('accounts:login_app')

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserAndProfileForm
    template_name = 'accounts/profile_update.html' # Замените на имя вашего шаблона
    success_url = reverse_lazy('accounts:about_me')

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.request.user.pk)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.save()
        profile, created = Profile.objects.get_or_create(user=user)
        profile.bio = form.cleaned_data.get('bio')
        profile.argumet_acsepted = form.cleaned_data.get('argumet_acsepted')
        profile.avatar = form.cleaned_data.get('avatar')
        profile.save()
        return super().form_valid(form)

FoodBook/accounts/templates/accounts/about-my.html
{% extends 'RecipeAndProduct/base_R&P.html'%}
{% load cache %}
{%block title%}
    <title>Профиль</title>
{% endblock %}

{%block body%}
    <div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      {% if user.is_authenticated %}
        <div class="card mb-4">
          <div class="card-header">
            <h2>Профиль</h2>
          </div>
          <div class="card-body">
            <div class="text-center mb-4">

                {% if user.profile.avatar %}
                  <img src="{{ user.profile.avatar.url }}" class="img-fluid rounded-circle" style="max-width: 200px;" alt="{{ user.username }}">
                {% else %}
                  <i class="bi bi-person-circle" style="font-size: 100px;"></i>
                {% endif %}

            </div>
            <dl class="row">

                <dt class="col-sm-3">Имя пользователя:</dt>
                <dd class="col-sm-9">{{ user.username }}</dd>

                <dt class="col-sm-3">Имя:</dt>
                <dd class="col-sm-9">{{ user.first_name }}</dd>

                <dt class="col-sm-3">Фамилия:</dt>
                <dd class="col-sm-9">{{ user.last_name }}</dd>

                <dt class="col-sm-3">Email:</dt>
                <dd class="col-sm-9">{{ user.email }}</dd>

                <dt class="col-sm-3">О себе:</dt>
                <dd class="col-sm-9">{{ user.profile.bio }}</dd>
            </dl>
            <a href="{% url 'accounts:about_me_update' %}" class="btn btn-primary mt-3">Обновить профиль</a>
          </div>
        </div>
      {% else %}
        <div class="alert alert-info mt-4" role="alert">
          <p>Пожалуйста, авторизируйтесь, чтобы просмотреть свой профиль.</p>
          <a href="{% url 'accounts:login_app' %}" class="btn btn-primary">Авторизация</a>
        </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

FoodBook/accounts/templates/accounts/error-cournt-request.html
{% extends 'RecipeAndProduct/base_R&P.html'%}


{% block title%}
    <title>Error</title>
{% endblock %}

{% block body%}
    <h1>Частые запросы. Подождите 10 секунд</h1>
{% endblock %}

FoodBook/accounts/templates/accounts/login_myauth.html
{% extends 'RecipeAndProduct/base_R&P.html'%}

{% block title%}
    <title>Login</title>
{% endblock%}

{% block body %}
     <form  method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Login</button>
    </form>
{% endblock%}

FoodBook/accounts/templates/accounts/profile_update.html
{% extends 'RecipeAndProduct/base_R&P.html'%}

{%block title%}
    <title>Редоктирование профиля</title>
{% endblock %}

{%block body%}

    <h1>Замените данные:</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Обновить">
    </form>
{% endblock %}

FoodBook/accounts/templates/accounts/register_user.html
{% extends 'RecipeAndProduct/base_R&P.html'%}

{%block title%}
    <title>Регистрация</title>
{% endblock %}

{%block body%}
    <h1>Укажите ваши данные:</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Зарегестрирвоаться">
    </form>
{% endblock %}